version: '3.5'

# for development purposes only, start with `docker-compose up --build` then head to localhost:9000
services:
    app:
        image: |SLUG|-dev
        build:
            context: .
            args:
                - APP_URL=http://localhost:9000
        ports:
            - 9000:80
        healthcheck:
            test: ["CMD-SHELL", "nc -z 127.0.0.1 80 || exit 1"]
            interval: 30s
            start_period: 1m
        restart: always
