//
//  Bundle+Harbor.swift
//  
//
//  Created by syan on 22/02/2023.
//

import Foundation

extension Bundle {
    static var moduleBundleAvailable: Bool {
        // taken from the autogenerated `resource_bundle_accessor.swift`
        #if os(macOS)
        let bundleName = "Harbor_Harbor.bundle"
        #else
        let bundleName = "Harbor_Harbor.resources"
        #endif
        let baseURL = Bundle.main.bundleURL
        let bundleURL = baseURL.appendingPathComponent(bundleName)
        print(bundleURL)
        return Bundle(url: bundleURL) != nil
    }
}
